---
galaxy_info:
  author: John Paul Newman
  description: Elasticsearch
  license: license (BSD, MIT)
  min_ansible_version: 2.0
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
    - elk
    - elasticsearch

dependencies: []
