---
# Necessary for Ubuntu 16.04
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: False
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

# For a local playbook run:  ansible-playbook -i "localhost," -c local --ask-sudo-pass playbooks/setup-openvpn.yml
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - openvpn
  vars:
    openvpn_use_pam: yes
    openvpn_proto: "tcp"
    openvpn_topology: "subnet"
    openvpn_server_options:
      - push "route 10.10.0.0 255.255.0.0"

